# Generated by Django 4.1 on 2022-09-07 08:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('logo_url', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('address', models.TextField(default='')),
            ],
        ),
    ]
