# Generated by Django 4.0.6 on 2022-07-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.CharField(auto_created='0e803367-16e0-45bf-be6e-772984ad5903', max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('logo_url', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('address', models.TextField(default='')),
            ],
        ),
    ]
