# Generated by Django 4.0.6 on 2022-07-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_id',
            field=models.CharField(auto_created='1428216d-5b97-492a-a23e-3fbf733cefc8', max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
