# Generated by Django 4.0.6 on 2022-07-23 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
