# Generated by Django 4.0.6 on 2022-07-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_phonetoken_token_id_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonetoken',
            name='token_id',
            field=models.CharField(default='c0fc0049-1f4e-4537-a70a-766b6bde753f', max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='c8164859-999d-4711-9ea8-87f183d74e04', max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
