# Generated by Django 4.0.6 on 2022-07-23 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_organization_user_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator(message='only digits and numbers allowed.', regex='^[a-zA-Z0-9]+([._]?[a-zA-Z0-9]+)*$')]),
        ),
    ]
