# Generated by Django 4.1 on 2022-09-07 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUnit',
            fields=[
                ('inventory_unit_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=500)),
                ('description', models.TextField(default='')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('inventory_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=500)),
                ('code', models.CharField(default='', max_length=500, unique=True)),
                ('description', models.TextField(default='')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organization.organization')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.inventoryunit')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryChangeModel',
            fields=[
                ('inventory_change_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('price_per_unit', models.FloatField(default=0.0)),
                ('quantity', models.FloatField(default=0.0)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.inventorymodel')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organization.organization')),
            ],
        ),
    ]
