# Generated by Django 4.0.6 on 2022-07-23 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0004_alter_organization_organization_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('inventory_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=500)),
                ('description', models.TextField(default='')),
                ('unit', models.CharField(default='piece', max_length=50)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organization.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryChangeModel',
            fields=[
                ('inventory_change_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('price_per_unit', models.FloatField(default=0.0)),
                ('quantity', models.FloatField(default=0.0)),
                ('deleted', models.BooleanField(default=False)),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.inventorymodel')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organization.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
