# Generated by Django 4.1 on 2022-09-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymodel',
            name='max',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='inventorymodel',
            name='min',
            field=models.CharField(default='', max_length=500),
        ),
    ]
